---
create_user: roman

copy_local_key: "{{ lookup('file', lookup('env','HOME') + '/.ssh/id_rsa.pub') }}"

sys_packages: [ 'curl', 'vim', 'git', 'zsh', 'net-tools', 'golang', 'python3', 'awscli', 'libtool', 'cmake']
